import { Edit3, Plus, Search, Star, Trash2, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { AppShell } from '../components/AppShell';
import { usePhoneStore } from '../state/usePhoneStore';
import type { Contact } from '../types';

export function ContactsApp(){
  const contacts=usePhoneStore((s)=>s.contacts);const add=usePhoneStore((s)=>s.addContact);const update=usePhoneStore((s)=>s.updateContact);const remove=usePhoneStore((s)=>s.deleteContact);
  const [query,setQuery]=useState('');const [editing,setEditing]=useState<Partial<Contact>|null>(null);const [error,setError]=useState('');
  const filtered=useMemo(()=>contacts.filter((c)=>`${c.name} ${c.phone}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(Boolean(b.favorite))-Number(Boolean(a.favorite))||a.name.localeCompare(b.name,'ru')),[contacts,query]);
  const save=()=>{if(!editing)return;if(!editing.name?.trim()){setError('Введите имя');return;}if(!editing.phone?.match(/[0-9]{3}/)){setError('Введите корректный номер');return;}if(editing.id)update(editing.id,editing);else add({name:editing.name.trim(),phone:editing.phone,email:editing.email,favorite:editing.favorite});setEditing(null);setError('');};
  return <AppShell title="Контакты" actions={<button aria-label="Добавить контакт" onClick={()=>setEditing({name:'',phone:'',email:'',favorite:false})}><Plus/></button>}><div className="px-4"><div className="mb-4 flex items-center gap-2 rounded-full bg-[var(--surface)] px-4"><Search size={17}/><input aria-label="Поиск контактов" value={query} onChange={(e)=>setQuery(e.target.value)} className="h-11 flex-1 bg-transparent outline-none" placeholder="Имя или номер"/></div>{filtered.map((c)=><div key={c.id} className="mb-2 flex items-center gap-3 rounded-[24px] bg-[var(--surface)] p-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-[var(--accent)]/20 text-lg">{c.name[0]}</span><button onClick={()=>usePhoneStore.getState().openApp('phone')} className="min-w-0 flex-1 text-left"><strong className="flex items-center gap-2">{c.name}{c.favorite&&<Star size={14} className="fill-amber-400 text-amber-400"/>}</strong><small className="opacity-50">{c.phone}</small></button><button aria-label={`Редактировать ${c.name}`} onClick={()=>setEditing(c)}><Edit3 size={18}/></button><button aria-label={`Удалить ${c.name}`} onClick={()=>confirm(`Удалить ${c.name}?`)&&remove(c.id)} className="text-red-400"><Trash2 size={18}/></button></div>)}</div>{editing&&<div className="absolute inset-0 z-20 bg-[var(--app-bg)] p-5 pt-14"><div className="flex justify-between"><h2 className="text-xl font-semibold">{editing.id?'Изменить контакт':'Новый контакт'}</h2><button onClick={()=>setEditing(null)}><X/></button></div><div className="mt-7 space-y-4"><label className="block text-sm">Имя<input aria-label="Имя контакта" value={editing.name??''} onChange={(e)=>setEditing({...editing,name:e.target.value})} className="mt-2 h-12 w-full rounded-2xl bg-[var(--surface)] px-4 outline-none"/></label><label className="block text-sm">Телефон<input aria-label="Телефон контакта" value={editing.phone??''} onChange={(e)=>setEditing({...editing,phone:e.target.value})} className="mt-2 h-12 w-full rounded-2xl bg-[var(--surface)] px-4 outline-none"/></label><label className="block text-sm">Email<input aria-label="Email контакта" type="email" value={editing.email??''} onChange={(e)=>setEditing({...editing,email:e.target.value})} className="mt-2 h-12 w-full rounded-2xl bg-[var(--surface)] px-4 outline-none"/></label><label className="flex items-center gap-3 rounded-2xl bg-[var(--surface)] p-4"><input type="checkbox" checked={Boolean(editing.favorite)} onChange={(e)=>setEditing({...editing,favorite:e.target.checked})}/>Избранный контакт</label>{error&&<p className="text-sm text-red-400">{error}</p>}<button onClick={save} className="w-full rounded-full bg-[var(--accent)] py-3 font-semibold text-zinc-950">Сохранить</button></div></div>}</AppShell>;
}
