import { BarChart3, Pause, Play, Repeat2, SkipBack, SkipForward, Volume2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { AppShell } from '../components/AppShell';
import { usePhoneStore } from '../state/usePhoneStore';

export function MusicApp() {
  const tracks=usePhoneStore((s)=>s.tracks); const currentId=usePhoneStore((s)=>s.currentTrackId); const setCurrent=usePhoneStore((s)=>s.setCurrentTrack);
  const [playing,setPlaying]=useState(false); const [progress,setProgress]=useState(0); const [volume,setVolume]=useState(.35); const [eq,setEq]=useState([.7,.4,.8,.5,.65]); const [repeat,setRepeat]=useState(false);
  const contextRef=useRef<AudioContext|null>(null); const oscRef=useRef<OscillatorNode|null>(null); const gainRef=useRef<GainNode|null>(null);
  const track=tracks.find((t)=>t.id===currentId)??tracks[0];
  const stopSound=()=>{try{oscRef.current?.stop();}catch{} oscRef.current=null;};
  const startSound=()=>{stopSound(); const ctx=contextRef.current??new AudioContext();contextRef.current=ctx; const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type='sine';osc.frequency.value=track.frequency;gain.gain.value=volume*.08;osc.connect(gain).connect(ctx.destination);osc.start();oscRef.current=osc;gainRef.current=gain;};
  useEffect(()=>{if(playing)startSound();else stopSound();return stopSound;},[playing,currentId]);
  useEffect(()=>{if(gainRef.current)gainRef.current.gain.value=volume*.08;},[volume]);
  useEffect(()=>{if(!playing)return;const t=setInterval(()=>setProgress((p)=>{if(p>=track.duration){if(repeat)return 0;const index=tracks.findIndex((x)=>x.id===track.id);setCurrent(tracks[(index+1)%tracks.length].id);return 0;}return p+1;}),1000);return()=>clearInterval(t);},[playing,track.id,track.duration,repeat,tracks,setCurrent]);
  const change=(delta:number)=>{const i=tracks.findIndex((x)=>x.id===track.id);setCurrent(tracks[(i+delta+tracks.length)%tracks.length].id);setProgress(0);};
  return <AppShell title="Samsung Music" actions={<BarChart3/>}><div className="px-5"><div className="mx-auto mt-5 aspect-square max-w-[320px] rounded-[38px] bg-gradient-to-br from-purple-500 via-indigo-600 to-cyan-500 p-7 shadow-2xl"><div className="flex h-full items-end rounded-[28px] bg-black/20 p-5"><div><p className="text-xs uppercase tracking-[.25em] text-white/60">Galaxy Sessions</p><p className="mt-2 text-3xl font-light text-white">{track.title}</p></div></div></div><div className="mt-7 text-center"><h2 className="text-2xl font-semibold">{track.title}</h2><p className="opacity-55">{track.artist}</p></div><input aria-label="Позиция трека" type="range" min="0" max={track.duration} value={progress} onChange={(e)=>setProgress(Number(e.target.value))} className="range mt-6 w-full"/><div className="flex justify-between text-xs opacity-45"><span>{format(progress)}</span><span>{format(track.duration)}</span></div><div className="mt-6 flex items-center justify-around"><button aria-label="Повтор" onClick={()=>setRepeat(!repeat)} className={repeat?'text-[var(--accent)]':'opacity-50'}><Repeat2/></button><button aria-label="Предыдущий трек" onClick={()=>change(-1)}><SkipBack size={30}/></button><button aria-label={playing?'Пауза':'Воспроизвести'} onClick={()=>setPlaying(!playing)} className="grid h-16 w-16 place-items-center rounded-full bg-[var(--accent)] text-zinc-950">{playing?<Pause size={30}/>:<Play size={30}/>}</button><button aria-label="Следующий трек" onClick={()=>change(1)}><SkipForward size={30}/></button><span className="w-6"/></div><label className="mt-6 flex items-center gap-3"><Volume2 size={18}/><input aria-label="Громкость музыки" className="range flex-1" type="range" min="0" max="1" step=".01" value={volume} onChange={(e)=>setVolume(Number(e.target.value))}/></label><div className="mt-6 rounded-[28px] bg-[var(--surface)] p-4"><p className="mb-4 text-sm font-semibold">Эквалайзер</p><div className="flex h-24 items-end justify-around">{eq.map((v,i)=><input key={i} aria-label={`Полоса эквалайзера ${i+1}`} type="range" min="0" max="1" step=".05" value={v} onChange={(e)=>setEq((old)=>old.map((x,j)=>j===i?Number(e.target.value):x))} className="range h-20 w-5 -rotate-90"/>)}</div></div><div className="mt-5 space-y-2">{tracks.map((t)=><button key={t.id} onClick={()=>{setCurrent(t.id);setProgress(0);}} className={`flex w-full items-center gap-3 rounded-2xl p-3 text-left ${t.id===track.id?'bg-[var(--accent)]/15':'bg-[var(--surface)]'}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-purple-500 to-cyan-500">♪</span><span className="flex-1"><strong className="block">{t.title}</strong><small className="opacity-50">{t.artist}</small></span><span className="text-xs opacity-45">{format(t.duration)}</span></button>)}</div></div></AppShell>;
}
const format=(seconds:number)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
