import { Bold, Eye, Italic, List, Plus, Save, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { AppShell } from '../components/AppShell';
import { usePhoneStore } from '../state/usePhoneStore';

function escapeHtml(value:string){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');}
function renderMarkdown(text:string){return text.split('\n').map((line,i)=>{const safe=escapeHtml(line);const html=safe.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/_(.+?)_/g,'<em>$1</em>');return <p key={i} className={line.startsWith('- ')?'ml-4 before:mr-2 before:content-["•"]':''} dangerouslySetInnerHTML={{__html:html.replace(/^- /,'')}}/>;});}
export function NotesApp(){
  const notes=usePhoneStore((s)=>s.notes);const add=usePhoneStore((s)=>s.addNote);const update=usePhoneStore((s)=>s.updateNote);const remove=usePhoneStore((s)=>s.deleteNote);
  const [editor,setEditor]=useState<{id?:string;title:string;body:string}|null>(null);const [preview,setPreview]=useState(false);const [textarea,setTextarea]=useState<HTMLTextAreaElement|null>(null);
  const wrap=(before:string,after=before)=>{if(!editor||!textarea)return;const start=textarea.selectionStart,end=textarea.selectionEnd;const next=editor.body.slice(0,start)+before+editor.body.slice(start,end)+after+editor.body.slice(end);setEditor({...editor,body:next});requestAnimationFrame(()=>{textarea.focus();textarea.setSelectionRange(start+before.length,end+before.length);});};
  const save=()=>{if(!editor)return;if(editor.id)update(editor.id,editor.title||'Без названия',editor.body);else add(editor.title||'Без названия',editor.body);setEditor(null);setPreview(false);};
  return <AppShell title="Samsung Notes" actions={<button aria-label="Новая заметка" onClick={()=>setEditor({title:'',body:''})}><Plus/></button>}><div className="grid grid-cols-2 gap-3 px-4">{notes.map((note)=><button key={note.id} onClick={()=>setEditor(note)} className="min-h-40 rounded-[26px] bg-amber-300 p-4 text-left text-zinc-900 shadow"><strong className="block truncate">{note.title}</strong><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm opacity-70">{note.body}</p><small className="mt-4 block text-[10px] opacity-50">{note.updatedAt}</small></button>)}</div>{editor&&<div className="absolute inset-0 z-20 flex flex-col bg-[var(--app-bg)] p-4 pt-12"><div className="flex items-center gap-2"><input aria-label="Заголовок заметки" value={editor.title} onChange={(e)=>setEditor({...editor,title:e.target.value})} className="h-12 min-w-0 flex-1 bg-transparent text-2xl font-semibold outline-none" placeholder="Заголовок"/><button aria-label="Предпросмотр" onClick={()=>setPreview(!preview)}><Eye/></button><button aria-label="Закрыть редактор" onClick={()=>setEditor(null)}><X/></button></div><div className="mb-3 flex gap-2 rounded-full bg-[var(--surface)] p-2"><button aria-label="Жирный текст" onClick={()=>wrap('**')} className="grid h-9 w-9 place-items-center rounded-full hover:bg-white/10"><Bold/></button><button aria-label="Курсив" onClick={()=>wrap('_')} className="grid h-9 w-9 place-items-center rounded-full hover:bg-white/10"><Italic/></button><button aria-label="Маркированный список" onClick={()=>wrap('- ','')} className="grid h-9 w-9 place-items-center rounded-full hover:bg-white/10"><List/></button><button aria-label="Удалить заметку" onClick={()=>{if(editor.id&&confirm('Удалить заметку?'))remove(editor.id);setEditor(null);}} className="ml-auto grid h-9 w-9 place-items-center rounded-full text-red-400"><Trash2/></button></div>{preview?<div className="flex-1 overflow-auto rounded-[24px] bg-[var(--surface)] p-4 leading-relaxed">{renderMarkdown(editor.body)}</div>:<textarea ref={setTextarea} aria-label="Текст заметки" value={editor.body} onChange={(e)=>setEditor({...editor,body:e.target.value})} className="flex-1 resize-none rounded-[24px] bg-[var(--surface)] p-4 leading-relaxed outline-none" placeholder="Начните писать..."/>}<button data-testid="save-note" onClick={save} className="mt-3 flex items-center justify-center gap-2 rounded-full bg-[var(--accent)] py-3 font-semibold text-zinc-950"><Save size={18}/>Сохранить</button></div>}</AppShell>;
}
